function [pos_joint, A_i_0] = ForwardKinematics(theta1, theta2, theta3, theta4, robot_config)
    % A_i_0 = struct();

    L1 = robot_config.robot_length.L1;
    L2 = robot_config.robot_length.L2;
    L3 = robot_config.robot_length.L3;
    L4 = robot_config.robot_length.L4;
    L5 = robot_config.robot_length.L5; 

    % clear; close all; clc;
    % syms L1 L2 L3 L4 L5 theta1 theta2 theta3 theta4 theta5 ai alphai di thetai;
    % 
    % A = [cos(thetai) -cos(alphai)*sin(thetai)  sin(alphai)*sin(thetai) ai*cos(thetai) ;...
    %      sin(thetai)  cos(alphai)*cos(thetai) -sin(alphai)*cos(thetai) ai*sin(thetai) ;...
    %      0            sin(alphai)              cos(alphai)             di             ;...         
    %      0            0                        0                       1             ];  
    % 
    % A_1_0 = subs(A, [ai, alphai, di, thetai], [0, pi/2, L1, theta1]);
    % A_2_1 = subs(A, [ai, alphai, di, thetai], [L2, 0, 0, theta2]);
    % A_3_2 = subs(A, [ai, alphai, di, thetai], [L3, 0, 0, -pi/2]);
    % A_4_3 = subs(A, [ai, alphai, di, thetai], [L4, 0, 0, theta3]);
    % A_5_4 = subs(A, [ai, alphai, di, thetai], [L5, 0, 0, theta4]);
    % A_1_0 = simplify(A_1_0);
    % A_2_0 = simplify(A_1_0 * A_2_1);
    % A_3_0 = simplify(A_1_0 * A_2_1 * A_3_2);
    % A_4_0 = simplify(A_1_0 * A_2_1 * A_3_2 * A_4_3);
    % A_5_0 = simplify(A_1_0 * A_2_1 * A_3_2 * A_4_3 * A_5_4);

    A_1_0 =...
    [cos(theta1), 0,  sin(theta1),  0;...
     sin(theta1), 0, -cos(theta1),  0;...
               0, 1,            0, L1;...
               0, 0,            0,  1];

    A_2_0 =...
    [cos(theta1)*cos(theta2), -cos(theta1)*sin(theta2),  sin(theta1), L2*cos(theta1)*cos(theta2);...
     cos(theta2)*sin(theta1), -sin(theta1)*sin(theta2), -cos(theta1), L2*cos(theta2)*sin(theta1);...
                 sin(theta2),              cos(theta2),            0,        L1 + L2*sin(theta2);...
                           0,                        0,            0,                          1];

    A_3_0 =...
    [cos(theta1)*sin(theta2), cos(theta1)*cos(theta2),  sin(theta1), cos(theta1)*(L2*cos(theta2) + L3*sin(theta2));...
     sin(theta1)*sin(theta2), cos(theta2)*sin(theta1), -cos(theta1), sin(theta1)*(L2*cos(theta2) + L3*sin(theta2));...
                -cos(theta2),             sin(theta2),            0,          L1 - L3*cos(theta2) + L2*sin(theta2);...
                           0,                       0,            0,                                             1];

    A_4_0 =...
    [sin(theta2 + theta3)*cos(theta1), cos(theta2 + theta3)*cos(theta1),  sin(theta1), cos(theta1)*(L4*sin(theta2 + theta3) + L2*cos(theta2) + L3*sin(theta2));...
     sin(theta2 + theta3)*sin(theta1), cos(theta2 + theta3)*sin(theta1), -cos(theta1), sin(theta1)*(L4*sin(theta2 + theta3) + L2*cos(theta2) + L3*sin(theta2));...
                -cos(theta2 + theta3),             sin(theta2 + theta3),            0,          L1 - L4*cos(theta2 + theta3) - L3*cos(theta2) + L2*sin(theta2);...
                                    0,                                0,            0,                                                                       1];

    A_5_0 =...
    [sin(theta2 + theta3 + theta4)*cos(theta1), cos(theta2 + theta3 + theta4)*cos(theta1),  sin(theta1), cos(theta1)*(L4*sin(theta2 + theta3) + L2*cos(theta2) + L3*sin(theta2) + L5*sin(theta2 + theta3 + theta4));...
     sin(theta2 + theta3 + theta4)*sin(theta1), cos(theta2 + theta3 + theta4)*sin(theta1), -cos(theta1), sin(theta1)*(L4*sin(theta2 + theta3) + L2*cos(theta2) + L3*sin(theta2) + L5*sin(theta2 + theta3 + theta4));...
                -cos(theta2 + theta3 + theta4),             sin(theta2 + theta3 + theta4),            0,          L1 - L4*cos(theta2 + theta3) - L3*cos(theta2) + L2*sin(theta2) - L5*cos(theta2 + theta3 + theta4);...
                                             0,                                         0,            0,                                                                                                          1];
    
    pos_joint =...
    [         0,          0,          0;...
     A_1_0(1,4), A_1_0(2,4), A_1_0(3,4);...
     A_2_0(1,4), A_2_0(2,4), A_2_0(3,4);...
     A_3_0(1,4), A_3_0(2,4), A_3_0(3,4);...
     A_4_0(1,4), A_4_0(2,4), A_4_0(3,4);...
     A_5_0(1,4), A_5_0(2,4), A_5_0(3,4)];

    % A_i_0 = {};
    A_i_0{1} = A_1_0;
    A_i_0{2} = A_2_0;
    A_i_0{3} = A_3_0;
    A_i_0{4} = A_4_0;
    A_i_0{5} = A_5_0;
end